In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
from sklearn.datasets import make_classification

In [21]:
X,y=make_classification(n_samples=100,n_features=20,n_classes=2,random_state=4)

In [22]:
X

array([[ 2.983269  , -1.50867081,  0.88093853, ..., -0.35973794,
         0.07488569,  1.01659065],
       [-0.20021697, -1.01617   ,  0.01319385, ..., -0.90057886,
        -1.5419175 ,  0.95693258],
       [ 0.69819327, -0.26422534, -0.31676444, ..., -1.44648213,
         0.48638511,  1.63240786],
       ...,
       [-1.40528445,  0.5337351 ,  0.10614917, ...,  1.08336528,
        -0.10993324, -0.46833785],
       [-1.32962257, -0.04394533, -0.45731792, ..., -0.40668098,
        -0.46723319, -0.67088397],
       [-0.48503067,  0.15583531, -1.31287282, ...,  1.60713209,
        -0.68035661, -0.79728302]])

In [23]:
y

array([0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0])

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=42)

In [26]:
from sklearn.linear_model import LogisticRegression

In [27]:
logistic=LogisticRegression()

In [28]:
logistic.fit(X_train,y_train)

LogisticRegression()

In [29]:
y_pred=logistic.predict(X_test)

In [30]:
y_pred

array([0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 1])

In [31]:
logistic.predict_proba(X_test)

array([[6.28896666e-01, 3.71103334e-01],
       [1.95132480e-01, 8.04867520e-01],
       [4.50215209e-02, 9.54978479e-01],
       [9.53543993e-01, 4.64560071e-02],
       [9.60631894e-01, 3.93681064e-02],
       [4.88666010e-01, 5.11333990e-01],
       [9.87415711e-01, 1.25842894e-02],
       [1.10359186e-01, 8.89640814e-01],
       [7.31951828e-02, 9.26804817e-01],
       [9.64442610e-01, 3.55573898e-02],
       [9.79441158e-01, 2.05588423e-02],
       [2.12040102e-02, 9.78795990e-01],
       [1.70652203e-01, 8.29347797e-01],
       [1.80149100e-01, 8.19850900e-01],
       [9.40034369e-02, 9.05996563e-01],
       [8.02314211e-02, 9.19768579e-01],
       [7.12301593e-01, 2.87698407e-01],
       [2.09217657e-02, 9.79078234e-01],
       [9.96665692e-01, 3.33430816e-03],
       [8.90815610e-01, 1.09184390e-01],
       [1.74539930e-02, 9.82546007e-01],
       [9.99454505e-01, 5.45494789e-04],
       [1.13385359e-01, 8.86614641e-01],
       [2.50296865e-01, 7.49703135e-01],
       [9.390434

In [32]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [33]:
score=accuracy_score(y_test,y_pred)

In [34]:
score

0.9

In [35]:
cm=confusion_matrix(y_test,y_pred)

In [36]:
cm

array([[11,  2],
       [ 1, 16]], dtype=int64)

In [37]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.92      0.85      0.88        13
           1       0.89      0.94      0.91        17

    accuracy                           0.90        30
   macro avg       0.90      0.89      0.90        30
weighted avg       0.90      0.90      0.90        30



## Hyperparameter Tuning and Cross Validation

In [53]:
model=LogisticRegression()
penalty=['l1','l2','elasticnet']
c_value=[100,10,1.0,0.1,0.01]
solver=['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga']
params=dict(penalty=penalty,C=c_value,solver=solver)


In [54]:
from sklearn.model_selection import StratifiedKFold
cv=StratifiedKFold()

In [55]:
from sklearn.model_selection import GridSearchCV
grid=GridSearchCV(estimator=model,param_grid=params,scoring='accuracy',cv=cv,n_jobs=-1)
grid.fit(X_train,y_train)

C:\Users\KIIT\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:547: FitFailedWarning: 
250 fits failed out of a total of 450.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\KIIT\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\KIIT\anaconda3\Lib\site-packages\sklearn\base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KIIT\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1172, in fit
    solver = _ch

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']},
             scoring='accuracy')

In [56]:
y_pred=grid.fit(X_train,y_train)

C:\Users\KIIT\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:547: FitFailedWarning: 
250 fits failed out of a total of 450.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\KIIT\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\KIIT\anaconda3\Lib\site-packages\sklearn\base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KIIT\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1172, in fit
    solver = _ch

In [58]:
grid.best_params_

{'C': 0.1, 'penalty': 'l1', 'solver': 'saga'}

In [60]:
grid.best_score_

0.9285714285714286

In [61]:
from sklearn.model_selection import RandomizedSearchCV

In [62]:
model=LogisticRegression()

In [64]:
randomCV=RandomizedSearchCV(estimator=model,param_distributions=params,cv=5,scoring='accuracy')

In [65]:
randomCV.fit(X_train,y_train)

C:\Users\KIIT\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:547: FitFailedWarning: 
40 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\KIIT\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\KIIT\anaconda3\Lib\site-packages\sklearn\base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KIIT\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1172, in fit
    solver = _check

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [100, 10, 1.0, 0.1, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['lbfgs', 'liblinear',
                                                   'newton-cg',
                                                   'newton-cholesky', 'sag',
                                                   'saga']},
                   scoring='accuracy')

In [66]:
randomCV.best_score_

0.7714285714285715

In [67]:
y_pred=randomCV.predict(X_test)

In [68]:
y_pred

array([0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 1])